# Map

engines = ["Google", "Bing", "Ask Jeeves"]
result = engines.map do |element|
  if element == "Google"
    element = "OK"
  elsif element == "Bing"
    element = "Bad!"
  else
    element = "What is that?"
  end
end

print result
# => ["OK", "Bad!", "What is that?"]

# The return value of .map is a new array that has been generated by the code in the block

# The return of .each is the original array unless specified otherwsise 